---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-tls
spec:
  secretName: gitlab-tls
  issuerRef:
    name: cloudflare-letsencrypt-staging
    kind: ClusterIssuer
  commonName: gitlab.dev.erpf.de
  dnsNames:
    - gitlab.dev.erpf.de
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "istio-system"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "istio-system"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-tls
spec:
  secretName: registry-tls
  issuerRef:
    name: cloudflare-letsencrypt-staging
    kind: ClusterIssuer
  commonName: registry.dev.erpf.de
  dnsNames:
    - registry.dev.erpf.de
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "istio-system"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "istio-system"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-tls
spec:
  secretName: minio-tls
  issuerRef:
    name: cloudflare-letsencrypt-staging
    kind: ClusterIssuer
  commonName: minio.dev.erpf.de
  dnsNames:
    - minio.dev.erpf.de
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "istio-system"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "istio-system"