---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "1m"
  target:
    name: postgres-credentials
  data:
  - secretKey: gitlab-password
    remoteRef:
      key: applications/postgresql
      property: gitlabPassword

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-credentials
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "1m"
  target:
    name: redis-credentials
  data:
  - secretKey: password
    remoteRef:
      key: applications/redis
      property: adminPassword