persistence:
  enabled: false
ingress:
  enabled: true
  hosts: 
    - host: vaultwarden.dev.erpf.de
    - host: bitwarden.dev.erpf.de
  tls:
    enabled: true
    redirect: false
  istioGateway:
    enabled: true
  certManager:
    enabled: true
    issuerRef: 
      name: cloudflare-letsencrypt-staging