gitlabReleaseName: gitlab-dev

persistence:
  volumes:
    - name: gitlab-dev-postgresql-data-0
      size: 8
      pv: data-gitlab-dev-postgresql-0
      pvc: data-gitlab-dev-postgresql-0
    - name: gitlab-dev-minio
      size: 10
      pv: gitlab-dev-minio
      pvc: 
    - name: gitlab-dev-prometheus-server
      size: 8
      pv: gitlab-dev-prometheus-server
      pvc: gitlab-dev-prometheus-server
    - name: gitlab-dev-redis-master-0
      size: 8
      pv: redis-data-gitlab-dev-redis-master-0
      pvc: redis-data-gitlab-dev-redis-master-0
    - name: gitlab-dev-gitaly-data-0
      size: 8
      pv: repo-data-gitlab-dev-gitaly-0
      pvc: repo-data-gitlab-dev-gitaly-0

ingress:
  enabled: true
  hosts:
    gitlab:
      - host: gitlab.dev.erpf.de
    registry:
      - host: registry.dev.erpf.de
    minio: 
      - host: minio.dev.erpf.de
  tls:
    enabled: true
    redirect: false
  istioGateway:
    enabled: true
  certManager:
    enabled: true
    issuerRef: 
      name: cloudflare-letsencrypt-staging