gitlabReleaseName: gitlab-dev

ingress:
  enabled: true
  hosts:
    gitlab:
      - host: gitlab.dev.erpf.de
    registry:
      - host: registry.dev.erpf.de
    minio: 
      - host: minio.dev.erpf.de
  tls:
    enabled: true
    redirect: false
  istioGateway:
    enabled: true
  certManager:
    enabled: true
    issuerRef: 
      name: cloudflare-letsencrypt-staging