global:
  edition: ce
  hosts:
    domain: dev.erpf.de # Provide a real base domain for GitLab. "gitlab." and "registry." will be exposed as subdomains.
    https: false
    # externalIP: "10.110.180.110" # If using a static wildcard DNS record for the base domain, enter the IP address it resolves to here.
    gitlab:
      # name: gitlab.example.com
      https: false
    registry:
      # name: registry.example.com
      https: false
    minio:
      # name: minio.example.com
      https: false
  ingress:
      configureCertmanager: false
      enabled: false

  # psql: # https://docs.gitlab.com/charts/advanced/external-db/
          # https://docs.gitlab.com/charts/charts/gitlab/migrations/index.html#postgresql
  #   host: postgresql-postgresql-ha-postgresql.postgresql.svc.athena.local
  #   username: gitlab
  #   password:
  #     secret: postgres-credentials
  #     key: gitlab-password
  #   database: gitlab

  # redis: # https://docs.gitlab.com/charts/advanced/external-redis/
           # https://docs.gitlab.com/charts/charts/gitlab/migrations/index.html#redis
  #   host: redis.redis.svc.athena.local
  #   password:
  #     secret: redis-credentials
  #     key: password

gitlab:
  certmanager: 
    install: false

  certmanager-issuer:
    email: letsencrypt@erpf.de # use your real email address here

  nginx-ingress:
    enabled: false

  # postgresql:
  #   install: false
  # redis:
  #   install: false

  gitlab:
    webservice: 
      ingress:
        tls:
          secretName: gitlab-dev-tls
    gitaly:
      persistence:
        size: "8Gi"

  registry:
    ingress:
      tls:
        secretName: registry-dev-tls

  minio:
    ingress:
      tls:
        secretName: minio-dev-tls
    persistence:
      volumeName: gitlab-umbrella-dev-minio # https://docs.gitlab.com/charts/charts/minio/
      storageClass: longhorn-static

  prometheus:
    server:
      persistentVolume:
        existingClaim: gitlab-umbrella-dev-prometheus-server # https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/values.yaml

persistence:
  volumes:
    - name: gitlab-dev-postgresql
      size: 8
      pv: data-gitlab-umbrella-dev-postgresql-0
      pvc: data-gitlab-umbrella-dev-postgresql-0
    - name: gitlab-dev-minio
      size: 10
      pv: gitlab-umbrella-dev-minio
      pvc: 
    - name: gitlab-dev-prometheus
      size: 8
      pv: gitlab-umbrella-dev-prometheus-server
      pvc: gitlab-umbrella-dev-prometheus-server
    - name: gitlab-dev-redis
      size: 8
      pv: redis-data-gitlab-umbrella-dev-redis-master-0
      pvc: redis-data-gitlab-umbrella-dev-redis-master-0
    - name: gitlab-dev-gitaly
      size: 8
      pv: repo-data-gitlab-umbrella-dev-gitaly-0
      pvc: repo-data-gitlab-umbrella-dev-gitaly-0

ingress:
  enabled: true
  hosts:
    gitlab:
      - host: gitlab.dev.erpf.de
    registry:
      - host: registry.dev.erpf.de
    minio: 
      - host: minio.dev.erpf.de
  tls:
    enabled: true
    redirect: false
  istioGateway:
    enabled: true
  certManager:
    enabled: true
    issuerRef: 
      name: cloudflare-letsencrypt-staging