---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "1m"
  target:
    name: postgres-credentials
  data:
  - secretKey: postgresUser
    remoteRef:
      key: applications/postgresql
      property: postgresUser
  - secretKey: postgresPassword
    remoteRef:
      key: applications/postgresql
      property: postgresPassword

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repmgr-credentials
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "1m"
  target:
    name: repmgr-credentials
  data:
  - secretKey: repmgrUser
    remoteRef:
      key: applications/postgresql
      property: repmgrUser
  - secretKey: repmgrPassword
    remoteRef:
      key: applications/postgresql
      property: repmgrPassword

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgpool-credentials
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "1m"
  target:
    name: pgpool-credentials
  data:
  - secretKey: adminUser
    remoteRef:
      key: applications/postgresql
      property: adminUser
  - secretKey: adminPassword
    remoteRef:
      key: applications/postgresql
      property: adminPassword
