---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "1m"
  target:
    name: postgres-credentials
  data:
  - secretKey: postgresql-password
    remoteRef:
      key: applications/postgresql
      property: postgresPassword
  - secretKey: repmgr-password
    remoteRef:
      key: applications/postgresql
      property: repmgrPassword
  - secretKey: admin-password
    remoteRef:
      key: applications/postgresql
      property: adminPassword
