---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubesphere-dev-tls
spec:
  secretName: kubesphere-dev-tls
  issuerRef:
    name: cloudflare-letsencrypt-staging
    kind: ClusterIssuer
  commonName: kubesphere.dev.erpf.de
  dnsNames:
    - kubesphere.dev.erpf.de
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"  
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "istio-system"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "istio-system"
