namespace: onlyoffice
helmGlobals:
  chartHome: /Users/jakoberpf/Code/jakoberpf/kubernetes/charts/charts
helmCharts:
- name: onlyoffice
  # repo: https://jakoberpf.github.io/charts/
  version: 0.0.1
  releaseName: onlyoffice
  namespace: onlyoffice
  valuesInline:
    enabled:
      community: true
      controlpanel: true
      documents: true
      mail: true
    mysql:
      clusterDomain: athena.local
    rabbitmq:
      clusterDomain: athena.local
    redis:
      clusterDomain: athena.local
    postgresql:
      clusterDomain: athena.local
    persistence:
      enabled: true
    ingress:
      enabled: true
      hosts: 
        - host: office.dev.erpf.de
      tls:
        enabled: true
        redirect: false
      istioGateway:
        enabled: true
      certManager:
        enabled: true
        issuerRef: 
          name: cloudflare-letsencrypt-prod
resources:
  - namespace.yaml