---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-credentials
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: "1m"
  target:
    name: mysql-credentials
  data:
  - secretKey: mysql-password
    remoteRef:
      key: applications/mysql
      property: password
  - secretKey: mysql-root-password
    remoteRef:
      key: applications/mysql
      property: root-password
  - secretKey: mysql-replication-password
    remoteRef:
      key: applications/mysql
      property: replication-password
